import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { User, UserSchema } from 'src/schemas/User.schema';
import { UsersService } from './users.service';
import { UsersController } from './users.controller';
import { UserSettings, UserSettingsSchema } from 'src/schemas/UserSettings.schema';

@Module({
    imports: [MongooseModule.forFeature([ //  This method is used to import Mongoose models into a specific NestJS module. It takes an array of objects, where each object represents a Mongoose model. In this case, you're providing an array with one object.
        { // this is a mongoose model
            name: User.name, // This specifies the name of the Mongoose model. The User class has a name property generated by NestJS that corresponds to the class name. This helps Mongoose identify the model. we can name this whatever we want
            schema: UserSchema // This associates the Mongoose model with a schema. The userSchema is the Mongoose schema created using decorators in the User class.
        },
        {
            name: UserSettings.name,
            schema: UserSettingsSchema
        }
    ])],
    controllers: [UsersController],
    providers: [UsersService]
})
export class UsersModule {}
